# Generated by Django 4.2.20 on 2025-04-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
